apiVersion: v1
kind: Service
metadata:
  name: hello-world-service-gitaction
spec:
  selector:
    app: helloworld
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30001
  type: NodePort
