name: Security Scan

on:
  pull_request:
    branches:
      - master

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Security Scan
      uses: github/codeql-action/analyze@v2
      with: {}
