name: Notifier

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    # #funziona a singola persona
    # notifyTelegram:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: send custom message
    #       uses: appleboy/telegram-action@master
    #       with:
    #         to: ${{ secrets.TELEGRAM_TO }} #da mettere id chat
    #         token: ${{ secrets.TELEGRAM_TOKEN }}
    #         message: |
    #           The ${{ github.event_name }} event triggered final step.
    #           echo This event is a pull request that had an assignee removed.

#   notifyTelegram:
#     runs-on: ubuntu-latest
#     steps:
#     # - name: Get channel members
#     #   id: get-members
#     #   run: |
#     #     curl -X GET "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/getChatMembersCount?chat_id=${{ secrets.TELEGRAM_CHAT }}" -o members.json
#     #     members=$(cat members.json | jq '.result')
#     #     echo "::set-output name=members::$members"
#     - name: Send message to channel members
#       id: send-message
#       run: |
#         curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TELEGRAM_CHAT }}" -d "text=Ciao! E' stato effettuato un nuovo commit nel repository. Vieni a vedere!"
#         # members=$(echo ${{ steps.get-members.outputs.members }})
#         # for member in $(seq 0 $(($members-1))); do
#         #     curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TELEGRAM_CHAT }}" -d "text=Hello member $member!"
#         # done

# #funziona a singola persona
#   notifyTelegram:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Notify on Commit
#         run: |
#             TELEGRAM_API_URL="https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage"
#             MESSAGE="Questo è un messaggio di notifica da GitHub Actions!"
            
#             curl -X POST -H "Content-Type: application/json" -d "{\"chat_id\":\"${{ secrets.TELEGRAM_CHAT }}\",\"text\":\"${MESSAGE}\"}" ${TELEGRAM_API_URL}

  get_channel_members:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Script
        run: python get_channel_members.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHANNEL_ID: -1001993783434  # Sostituisci con l'ID del tuo canale
